# Listas parcialmente ordenadas, tu nuevo superpoder
<img src="./img/superman.jpg" width="600">

In [1]:
import numpy as np
import pandas as pd
DATA_PATH = 'data/'

In [2]:
df = pd.read_csv(DATA_PATH + 'charcters_stats.csv')
df.shape

(611, 9)

In [3]:
sample_superheroes = ['Superman', 'Thor', 'Supergirl', 'Goku', 'Batman', 'Iron Man', 'Watcher', 'Joker', 'Wonder Woman', 'Magneto']
df[df['Name'].isin(sample_superheroes)]

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
61,Batman,good,100,18,27,42,37,100,324
251,Goku,good,56,100,75,90,100,100,521
299,Iron Man,good,100,85,58,85,100,64,492
315,Joker,bad,100,10,12,56,22,90,290
354,Magneto,bad,88,80,27,84,91,80,450
536,Supergirl,good,94,98,92,100,85,75,544
537,Superman,good,100,100,100,100,94,85,579
546,Thor,good,69,100,92,100,100,85,546
589,Watcher,good,100,80,67,89,100,56,492
600,Wonder Woman,good,88,100,50,100,42,100,480

In [4]:
# Muestra Total Top 60
df.sort_values("Total", ascending=False).head(60)

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total
361,Martian Manhunter,good,100,100,96,100,100,85,581
242,General Zod,bad,94,100,96,100,94,95,579
535,Superboy-Prime,bad,94,100,100,100,100,85,579
537,Superman,good,100,100,100,100,94,85,579
16,Amazo,bad,75,100,100,100,100,100,575
525,Stardust,good,88,85,100,110,100,85,568
238,Galactus,neutral,100,100,83,100,100,70,553
82,Bizarro,neutral,75,95,100,100,95,85,550
203,Dormammu,bad,88,95,83,100,100,80,546
546,Thor,good,69,100,92,100,100,85,546
201,Doomsday,bad,88,80,67,120,100,90,545
536,Supergirl,good,94,98,92,100,85,75,544
171,Cyborg Superman,bad,75,93,92,100,100,80,540
417,Nova,good,100,85,67,101,100,85,538
219,Faora,bad,88,95,75,100,87,90,535
356,Magus,bad,88,100,70,99,100,74,531
5,Abraxas,bad,88,100,83,99,100,56,526
84,Black Adam,bad,88,100,92,100,89,56,525
251,Goku,good,56,100,75,90,100,100,521
306,Jean Grey,good,100,80,67,100,100,70,517
433,Phoenix,good,100,80,67,100,100,70,517
218,Fallen One II,bad,88,85,83,100,100,56,512
180,Darkseid,bad,88,100,23,100,100,95,506
422,Onslaught,bad,88,85,47,100,100,85,505
365,Match,bad,75,95,83,85,90,70,498
26,Anti-Monitor,bad,88,90,38,90,100,90,496
29,Apocalypse,bad,100,100,33,100,100,60,493
589,Watcher,good,100,80,67,89,100,56,492
299,Iron Man,good,100,85,58,85,100,64,492
583,War Machine,good,63,80,63,100,100,85,491
438,Power Girl,good,88,98,67,95,67,75,490
534,Superboy,good,75,95,83,90,84,60,487
345,Lobo,bad,88,83,35,100,95,85,486
542,Thanos,bad,88,100,17,100,100,80,485
85,Black Bolt,good,75,67,100,84,100,56,482
547,Thor Girl,good,75,83,70,84,100,70,482
138,Captain Marvel,good,100,100,67,95,62,56,480
600,Wonder Woman,good,88,100,50,100,42,100,480
499,Silver Surfer,good,63,100,84,101,100,32,480
564,Ultron,bad,88,83,42,100,100,64,477
511,Spawn,good,75,60,50,90,100,95,470
578,Vision,good,100,72,54,95,76,70,467
70,Beyonder,good,88,100,23,100,100,56,467
604,X-Man,good,88,53,53,95,92,84,465
585,Warlock,good,88,36,79,95,71,95,464
281,Hercules,good,63,100,46,85,67,100,461
288,Hulk,good,88,100,47,100,41,85,461
191,Destroyer,bad,50,95,58,98,90,70,461
11,Air-Walker,bad,50,85,100,85,100,40,460
147,Century,good,88,80,53,64,74,100,459
28,Anti-Venom,NaN,75,60,65,90,85,84,459
293,Hyperion,good,63,95,75,95,58,72,458
69,Beta Ray Bill,good,63,80,35,95,100,84,457
383,Miss Martian,good,63,85,58,100,100,45,451
142,Carnage,bad,63,63,70,84,81,90,451
354,Magneto,bad,88,80,27,84,91,80,450
205,Ego,bad,88,80,83,99,71,28,449
486,Sentry,good,75,80,58,84,97,54,448
599,Wonder Man,good,75,100,53,90,64,64,446
327,Kilowog,good,81,90,53,42,100,80,446

In [5]:
df.describe().round(2)

       Intelligence  Strength   Speed  Durability   Power  Combat   Total
count        611.00    611.00  611.00      611.00  611.00  611.00  611.00
mean          44.50     29.08   27.31       41.84   40.31   43.21  226.25
std           32.92     32.61   25.76       36.54   34.54   33.27  167.32
min            1.00      1.00    1.00        1.00    0.00    1.00    5.00
25%            1.00      1.00    1.00        1.00    0.00    1.00    5.00
50%           50.00     10.00   23.00       32.00   37.00   50.00  255.00
75%           75.00     53.00   42.00       80.00   67.00   70.00  351.50
max          113.00    100.00  100.00      120.00  100.00  101.00  581.00

In [6]:
# POSET
attributes = ["Intelligence", "Strength", "Speed",  "Durability", "Power", "Combat"]
data = df[attributes].to_numpy()
n = data.shape[0]

dominated = np.zeros(n, dtype=bool)

for i in range(n):
    if dominated[i]:
        continue
    for j in range(n):
        if i == j:
            continue
        # j dominates i if j >= i on all dimensions and strictly > on at least one
        if np.all(data[j] >= data[i]) and np.any(data[j] > data[i]):
            dominated[i] = True
            break

df["non_dominated"] = ~dominated
df.shape

(611, 10)

In [7]:
df.sample(10, random_state=5)

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total,non_dominated
28,Anti-Venom,NaN,75,60,65,90,85,84,459,False
497,Silk Spectre I,good,1,1,1,1,0,1,5,False
322,Kevin 11,bad,25,7,12,14,100,40,198,False
499,Silver Surfer,good,63,100,84,101,100,32,480,True
123,Brainiac 5,good,100,10,23,28,60,32,253,False
53,Banshee,good,50,10,58,42,60,70,290,False
99,Blade,good,63,28,38,50,33,90,302,False
45,Atom II,good,1,1,1,1,0,1,5,False
328,Kingpin,bad,75,18,25,40,13,70,241,False
409,Nathan Petrelli,good,1,1,1,1,0,1,5,False

In [8]:
# Resultados
nd_count = df["non_dominated"].sum()
total = len(df)

summary = pd.DataFrame({
    "Total heroes": [total],
    "Non‑dominated": [nd_count],
    "Dominated": [total - nd_count],
    "Share non‑dominated (%)": [round(nd_count / total * 100, 3)]
})

summary

   Total heroes  Non‑dominated  Dominated  Share non‑dominated (%)
0           611             19        592                     3.11

In [9]:
nd = df[df["non_dominated"]].sort_values("Total", ascending=False)
nd

,Name,Alignment,Intelligence,Strength,Speed,Durability,Power,Combat,Total,non_dominated
361,Martian Manhunter,good,100,100,96,100,100,85,581,True
537,Superman,good,100,100,100,100,94,85,579,True
535,Superboy-Prime,bad,94,100,100,100,100,85,579,True
242,General Zod,bad,94,100,96,100,94,95,579,True
16,Amazo,bad,75,100,100,100,100,100,575,True
525,Stardust,good,88,85,100,110,100,85,568,True
201,Doomsday,bad,88,80,67,120,100,90,545,True
417,Nova,good,100,85,67,101,100,85,538,True
180,Darkseid,bad,88,100,23,100,100,95,506,True
26,Anti-Monitor,bad,88,90,38,90,100,90,496,True
499,Silver Surfer,good,63,100,84,101,100,32,480,True
600,Wonder Woman,good,88,100,50,100,42,100,480,True
147,Century,good,88,80,53,64,74,100,459,True
36,Ares,good,75,82,35,80,62,101,435,True
360,Mandarin,bad,100,28,23,28,99,95,373,True
449,Ra's Al Ghul,bad,100,28,32,42,27,100,329,True
61,Batman,good,100,18,27,42,37,100,324,True
315,Joker,bad,100,10,12,56,22,90,290,True
386,Mister Mxyzptlk,bad,113,10,12,14,100,28,277,True